spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/short_url
    username: root
    password: 123qwe!@#QWE
    driver-class-name: com.mysql.cj.jdbc.Driver

  output:
    ansi:
      enabled: always

logging:
  level:
    org:
      hibernate:
        SQL: debug
      springframework:
        web: info
server:
  port: 9090
